# Generated by Django 5.0.6 on 2024-05-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table='chats',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
