# Generated by Django 5.0.4 on 2024-05-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_chat_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(unique=True, verbose_name=255),
        ),
    ]
